### ISSUE TITLE
Newbie's issue...

### ISSUE THREAD

**Issue by Flo-63** [DougieLawson/Zappi_API#1]
After pulling the code, I wanted to CMake the API. Doing so, I get the following errors:

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
lib_curl
    linked by target "getup" in directory /root/zappi/Zappi_API
    linked by target "zparse" in directory /root/zappi/Zappi_API
lib_json-c
    linked by target "zparse" in directory /root/zappi/Zappi_API
lib_mariadb
    linked by target "dailyev" in directory /root/zappi/Zappi_API
    linked by target "zparse" in directory /root/zappi/Zappi_API

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

Unfortuantely, I`m not familiar wirh CMake environment - I cant fix this. CURL, json and mariadb are of course installed but I can't figure out how to set library paths to CMake. 

Many thanks!

**Comment by DougieLawson** [comment]
If you're building on DebIan or RaspiOS Bullseye
`sudo apt install libmariadb-dev libcurl-dev`
Then go and clone lib-json-c from https://github.com/json-c/json-c

That should get the three missing libraries.
